name: Workflow CI   
 
on:
  pull_request:
    branches:
      - main
  
 
jobs:
  build:
    name: test-checker
    runs-on: ubuntu-latest
 
    services:
      mysql:
        image: mysql:latest
        env:
          echo "MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}"
          echo "MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}"
          echo "MYSQL_USER: ${{ secrets.MYSQL_USER }}"
          echo "MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}"
          echo "MYSQL_HOST: ${{ secrets.MYSQL_HOST }}"
          echo "MYSQL_PORT: ${{ secrets.MYSQL_PORT }}"
          echo "MYSQL_DIALECT: ${{ secrets.MYSQL_DIALECT }}"
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
 
    strategy:
      matrix:
        node-version: [20.x]
 
    steps:
      - uses: actions/checkout@v2
 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
 
      - name: Install Dependencies
        run: npm install
 
      - name: Run npm start
        run: npm start
 
      - name: Run Tests
        run: npm test