name: Workflow CII

on:
  pull_request:
    #types: [closed]
    branches:
      - main

jobs:
  build:
    name: test-build
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:

      - name: Start MySQL
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql

      - name: Configure MySQL
        run: |
          sudo mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DB }};"
          sudo mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "CREATE USER IF NOT EXISTS '${{ secrets.DB_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}';"
          sudo mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "GRANT ALL PRIVILEGES ON ${{ secrets.DB }}.* TO '${{ secrets.DB_USER }}'@'localhost';"
          sudo mysql -u root -p"${{ secrets.MYSQL_ROOT_PASSWORD }}" -e "FLUSH PRIVILEGES;"

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up environment variables
        run: |
          echo "DB_USER=${{ secrets.DB_USER}}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB=${{ secrets.DB }}" >> .env
          echo "HOST=${{ secrets.HOST }}" >> .env
          echo "DIALECT=${{ secrets.DIALECT }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env

      - name: Install Dependencies
        run: npm install

      - name: Start the application
        run: |
            npm start &

      - name: Wait for the application to be ready
        run: |
            sleep 10
            until curl -s http://localhost:8080; do
              sleep 5
            done

      # - name: Run Tests
      #   run: npm test

      - name: Remove .env file
        run: rm .env

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Create webapp.zip
        run: |
            zip -r webapp.zip ./

      - name: Initialize Packer
        run: packer init packer-config/custom_image.pkr.hcl

      - name: Build custom image
        run:  packer build -var 'project_id=${{ secrets.GCP_PROJECT_ID }}'  packer-config/custom_image.pkr.hcl

      - name: Create Instance Template
        run: |
          # Read the manifest.json file and extract the image name
          image_list=$(gcloud compute images list --filter="name~'custom-image-.*'" --format="value(NAME, creationTimestamp)" | sort -k2 -r)

    
          # Extract latest image
          latest_image=$(echo "$image_list" | head -n1 | awk '{print $1}')

          echo "Latest Image: $latest_image"

          TEMPLATE="webapp-template-$(date +%Y%m%d%H%M%S)"

          gcloud compute instance-templates create $TEMPLATE \
            --machine-type=${{ secrets.MACHINE_TYPE }}\
            --image=$latest_image \
            --network=https://www.googleapis.com/compute/v1/projects/${{ secrets.GCP_PROJECT_ID }}/global/networks/${{ secrets.VPC_NAME }}  \
            --subnet=https://www.googleapis.com/compute/v1/projects/${{ secrets.GCP_PROJECT_ID }}/regions/${{ secrets.REGION }}/subnetworks/${{ secrets.SUBNET_NAME}} \
            --description="my-template" \
            --instance-template-region=${{ secrets.REGION }} \
            --boot-disk-type=${{ secrets.BOOT_DISK_TYPE }}  \
            --boot-disk-device-name=my-boot-disk \
            --boot-disk-size=${{ secrets.BOOT_DISK_SIZE }}  \
            --boot-disk-kms-key projects/${{ secrets.GCP_PROJECT_ID }}/locations/${{ secrets.REGION }}/keyRings/${{ secrets.KEY_RING }}/cryptoKeys/${{ secrets.KEY}}\
            --metadata=startup-script='#!/bin/bash
                    ENV_FILE="/opt/webapp/.env"
                    if [ ! -f "$ENV_FILE" ]; then
                      echo "HOST=${{ secrets.CHOST }}" > /opt/webapp/.env
                      echo "DB_PASSWORD=xXhhnwQbZ6j6Tr5E" >> /opt/webapp/.env
                      echo "DB_USER=${{ secrets.CDB_USER }}" >> /opt/webapp/.env
                      echo "DB=${{ secrets.CDB  }}" >> /opt/webapp/.env
                      echo "DIALECT=mysql" >> /opt/webapp/.env
                      echo "TOPIC_NAME=verify_email" >> /opt/webapp/.env
                      echo "LOGPATH=/var/log/webapp/app.log" >> /opt/webapp/.env
                    else
                      echo "$ENV_FILE file already exists."
                    fi
                    /opt/webapp/packer-config/configure_systemd.sh' \
            --tags=webapp \
            --service-account=${{ secrets.SERVICE_ACCOUNT }}@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --scopes="cloud-platform"

      

      - name: Start Rolling Update
        run: |
          gcloud compute instance-groups managed rolling-action start-update ${{ secrets.INSTANCE_TEMPLATE }} \
            --version=template=projects/${{ secrets.GCP_PROJECT_ID }}/regions/${{ secrets.REGION }}/instanceTemplates/$TEMPLATE \
            --region=${{ secrets.REGION }} \
            --type=proactive

      - name: Wait for Instance Refresh
        run: |
          # Wait for instance group refresh to complete
          gcloud compute instance-groups managed wait-until-stable ${{secrets.INSTANCE_TEMPLATE }} --region=${{ secrets.REGION }}
